version: "3.7"

services:
  #  mysql:
  #    image: mysql:8
  #    command: --default-authentication-plugin=mysql_native_password
  #    restart: always
  #    env_file:
  #      - .env.dev
  #    environment:
  #      MYSQL_DATABASE: ${DATABASE_NAME}
  #      MYSQL_USER: ${DATABASE_USER}
  #      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
  #      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
  #    volumes:
  #      - db_data:/var/lib/mysql
  #    ports:
  #      - ${DATABASE_PORT}:3306
  #  redis:
  #    image: 'redis'
  #    ports:
  #      - 6379:6379
  #    volumes:
  #      - redis_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env.dev
    command: [ "./main" ]
    volumes:
      - .:/code
    ports:
      - 8000:8000
#    depends_on:
#      - mysql
#      - redis

#volumes:
#  db_data:
#  redis_data: